# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5d2139ccf289b8dbd9d677a4a8f9831044f15c0776fd5ea887e71a0d4e719560b1953b243e1c603bd485bdfa7668a38fdb1d875d4fc77f60b9b26f2f9fa17fb

test:
  secret_key_base: b2750e04686edc5b3677b0f4e932d86307cdb55eea5b4e02bc4f6e7e961444ea83da4d0be8319773a6e9f62836c059d2d1a5541c23d4c0f89d80904b7aa46439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
